all:
	cd ctype; make all
	cd reent; make all
	cd stdio; make all
	cd stdlib; make all
	cd string; make all
	cd locale; make all
	cd trio; make all
	cd trutil; make all
	cd sys/sysvi386; make all
	cd libm/math; make all
	cd lib; make all
	
clean:
	cd ctype; make clean
	cd reent; make clean
	cd stdio; make clean
	cd stdlib; make clean
	cd string; make clean
	cd locale; make clean
	cd trio; make clean
	cd trutil; make clean
	cd sys/sysvi386; make clean
	cd libm/math; make clean
	cd lib; make clean
	